services:
  _defaults:
    autowire: true

  Sfmok\RequestInput\Factory\InputFactory: ~

  Sfmok\RequestInput\Factory\InputFactoryInterface: '@Sfmok\RequestInput\Factory\InputFactory'

  Sfmok\RequestInput\ArgumentResolver\InputArgumentResolver:
    tags:
      - { name: controller.argument_value_resolver, priority: 40 }

  Sfmok\RequestInput\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }