services:
  _defaults:
    autowire: true

  Sfmok\RequestInput\Factory\InputFactory:
    arguments:
      $skipValidation: '%request_input.skip_validation%'

  Sfmok\RequestInput\Metadata\InputMetadataFactory: ~

  Sfmok\RequestInput\Factory\InputFactoryInterface: '@Sfmok\RequestInput\Factory\InputFactory'

  Sfmok\RequestInput\Metadata\InputMetadataFactoryInterface: '@Sfmok\RequestInput\Metadata\InputMetadataFactory'

  Sfmok\RequestInput\ArgumentResolver\InputArgumentResolver:
    arguments:
      $inputFormats: '%request_input.formats%'
      $enabled: '%request_input.enabled%'
    tags:
      - { name: controller.argument_value_resolver, priority: 40 }

  Sfmok\RequestInput\EventListener\ExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  Sfmok\RequestInput\EventListener\ReadInputListener:
    arguments:
      $enabled: '%request_input.enabled%'
    tags:
      - { name: kernel.event_listener, event: kernel.controller }